# Generated by Django 6.1 on 2026-09-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
    ]
