# Generated by Django 5.2.17 on 2026-09-03 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatops', '0002_alter_conversation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_generated_id'), name='unique_client_message_per_conversation'),
        ),
    ]
