# Generated by Django 5.2.17 on 2026-09-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatops', '0003_message_unique_client_message_per_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='member_policy',
            field=models.CharField(choices=[('manual', 'Manual (members chosen explicitly)'), ('auto_all', 'All active users (auto-add & keep in sync)')], default='manual', help_text='How members are determined. AUTO_ALL adds every active user automatically and keeps them in sync.', max_length=20),
        ),
    ]
