# Generated by Django 6.1 on 2026-09-01 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Stable client-generated device identifier', max_length=100)),
                ('object_type', models.CharField(help_text="'report' | 'incident' | 'message' | 'attachment'", max_length=50)),
                ('client_generated_id', models.UUIDField()),
                ('server_object_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('duplicate', 'Duplicate (already applied)')], default='queued', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('device_captured_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='syncengine__status_b1ea34_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'object_type', 'client_generated_id'), name='unique_sync_item_per_device')],
            },
        ),
    ]
