# Generated by Django 6.1 on 2026-09-02 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('officials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundSmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_phone', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('gateway_message_id', models.CharField(blank=True, help_text="Provider's own message ID, if given", max_length=100)),
                ('gateway_provider', models.CharField(blank=True, max_length=50)),
                ('parse_result', models.CharField(choices=[('parsed', 'Parsed'), ('unparseable', 'Could not parse message format'), ('unknown_sender', 'Sender phone not linked to a field official'), ('unknown_polling_unit', 'Polling unit code not recognized')], max_length=32)),
                ('parse_note', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('matched_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='officials.official')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingSmsSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('report', 'Report'), ('incident', 'Incident')], max_length=16)),
                ('payload', models.JSONField(help_text='Normalized fields ready to become a Report/Incident on approval')),
                ('assignment_mismatch', models.BooleanField(default=False, help_text='True if the sending official has no active assignment to the stated polling unit')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('resulting_object_id', models.CharField(blank=True, help_text='ID of the Report/Incident created on approval', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_pending_submissions', to='officials.official')),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_pending_submissions', to='geography.pollingunit')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_reviews', to=settings.AUTH_USER_MODEL)),
                ('source_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_submission', to='smsgateway.inboundsmsmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inboundsmsmessage',
            index=models.Index(fields=['sender_phone'], name='smsgateway__sender__c7aa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundsmsmessage',
            index=models.Index(fields=['parse_result'], name='smsgateway__parse_r_85807a_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingsmssubmission',
            index=models.Index(fields=['status'], name='smsgateway__status_b6e900_idx'),
        ),
    ]
