# Generated by Django 6.1 on 2026-09-01 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='geography.state')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geography.lga')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('lga', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_code', models.CharField(help_text='Official INEC PU reference/code', max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location_description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('operational_status', models.CharField(choices=[('active_reporting', 'Active / Reporting'), ('recently_reported', 'Recently Reported'), ('report_overdue', 'Report Overdue'), ('incident_reported', 'Incident Reported'), ('awaiting_assignment', 'Awaiting Assignment'), ('official_offline', 'Official Offline')], default='awaiting_assignment', max_length=32)),
                ('data_version', models.PositiveIntegerField(default=1)),
                ('source_note', models.CharField(blank=True, help_text="e.g. 'INEC RA/PU list, 2026 release'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_units', to='geography.ward')),
            ],
            options={
                'ordering': ['ward__lga__name', 'ward__name', 'name'],
                'indexes': [models.Index(fields=['operational_status'], name='geography_p_operati_51e86b_idx'), models.Index(fields=['official_code'], name='geography_p_officia_d79b32_idx')],
            },
        ),
    ]
