# Generated by Django 6.1 on 2026-09-01 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_generated_id', models.UUIDField(help_text='Generated on-device at creation time, for dedup on sync')),
                ('operational_status', models.CharField(help_text='Snapshot of geography.OperationalStatus at submission time', max_length=32)),
                ('narrative', models.TextField(blank=True)),
                ('device_captured_at', models.DateTimeField(help_text='Timestamp set on-device when report was created')),
                ('server_received_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('saved_offline', 'Saved Offline'), ('synchronizing', 'Synchronizing'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='officials.official')),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='geography.pollingunit')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reportcategory')),
            ],
            options={
                'ordering': ['-device_captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='report_attachments/%Y/%m/')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Required Metadata'), (2, 'Supporting Image'), (3, 'Other Media')], default=2)),
                ('sync_status', models.CharField(choices=[('saved_offline', 'Saved Offline'), ('synchronizing', 'Synchronizing'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='saved_offline', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report')),
            ],
            options={
                'ordering': ['priority', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['sync_status'], name='reports_rep_sync_st_93fb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['polling_unit', '-device_captured_at'], name='reports_rep_polling_a06d7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('official', 'client_generated_id'), name='unique_client_report_per_official'),
        ),
    ]
