# Generated by Django 5.2.17 on 2026-09-03 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('incidents', '0001_initial'),
        ('officials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(fields=('reporter', 'client_generated_id'), name='unique_client_incident_per_reporter'),
        ),
    ]
