# Generated by Django 5.2.17 on 2026-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_overdue', 'Report Overdue'), ('new_incident', 'New Incident'), ('sync_complete', 'Synchronization Complete'), ('system_alert', 'System Alert'), ('message', 'New Message'), ('assignment_changed', 'Assignment Changed'), ('pu_request_submitted', 'Polling Unit Request Submitted'), ('pu_request_decided', 'Polling Unit Request Decision')], max_length=32),
        ),
    ]
